export const pageOptions = {
  scout: {
    title: 'Scout',
    pageTitle: 'Scout Soundboard',
    pageImage: 'Scoutava.png',
    icon: 'Scout_emblem_RED.png',
    pageName: 'scout',
    link: '/index/scout',
  },
  soldier: {
    title: 'Soldier',
    pageTitle: 'Soldier Soundboard',
    pageImage: 'Soldierava.png',
    icon: 'Soldier_emblem_RED.png',
    pageName: 'soldier',
    link: '/index/soldier',
  },
  pyro: {
    title: 'Pyro',
    pageTitle: 'Pyro Soundboard',
    pageImage: 'Pyroava.png',
    icon: 'Pyro_emblem_RED.png',
    pageName: 'pyro',
    link: '/index/pyro',
  },
  demoman: {
    title: 'Demoman',
    pageTitle: 'Demoman Soundboard',
    pageImage: 'Demomanava.png',
    icon: 'Demoman_emblem_RED.png',
    pageName: 'demoman',
    link: '/index/demoman',
  },
  heavy: {
    title: 'Heavy',
    pageTitle: 'Heavy Soundboard',
    pageImage: 'Heavyava.png',
    icon: 'Heavy_emblem_RED.png',
    pageName: 'heavy',
    link: '/index/heavy',
  },
  engineer: {
    title: 'Engineer',
    pageTitle: 'Engineer Soundboard',
    pageImage: 'Engineerava.png',
    icon: 'Engineer_emblem_RED.png',
    pageName: 'engineer',
    link: '/index/engineer',
  },
  medic: {
    title: 'Medic',
    pageTitle: 'Medic Soundboard',
    pageImage: 'Medicava.png',
    icon: 'Medic_emblem_RED.png',
    pageName: 'medic',
    link: '/index/medic',
  },
  sniper: {
    title: 'Sniper',
    pageTitle: 'Sniper Soundboard',
    pageImage: 'Sniperava.png',
    icon: 'Sniper_emblem_RED.png',
    pageName: 'sniper',
    link: '/index/sniper',
  },
  spy: {
    title: 'Spy',
    pageTitle: 'Spy Soundboard',
    pageImage: 'Spyava.png',
    icon: 'Spy_emblem_RED.png',
    pageName: 'spy',
    link: '/index/spy',
  },
  config: {
    title: 'Config',
    pageTitle: 'Config',
    pageImage: 'Configava.png',
    icon: 'Cog_emblem_RED.png',
    pageName: 'config',
    link: '/config',
  },
};
